import { FileText } from "lucide-react";
import LegalLayout from "./layout";

export default function TermsOfService() {
  return (
    <LegalLayout icon={FileText} title="Terms of Service" updated="March 5, 2026">
      <Section title="1. Acceptance of Terms">
        <p>
          By accessing or using the Borrowed Curiosity website and its services, you agree to
          be bound by these Terms of Service. If you do not agree, please do not use our site.
        </p>
      </Section>

      <Section title="2. Description of Services">
        <p>Borrowed Curiosity LLC provides:</p>
        <ul>
          <li>A blog with free articles on numerology, spirituality, and self-discovery.</li>
          <li>An online store selling handcrafted goods (salves, jewelry) and written numerology reports.</li>
          <li>Free numerology tools including a calculator, compatibility checker, daily guidance, gematria calculator, word lookup, and crystal guide.</li>
          <li>A chat assistant ("Alta") for numerology guidance.</li>
          <li>Free educational courses with community comments.</li>
          <li>A gallery and thread-based content section.</li>
        </ul>
      </Section>

      <Section title="3. User Accounts and Comments">
        <p>
          You do not need an account to use most features. When posting comments, you provide
          a display name. You are responsible for the content you post. We reserve the right
          to remove any content that is abusive, spam, or violates these terms.
        </p>
      </Section>

      <Section title="4. Store Purchases">
        <ul>
          <li>All prices are listed in USD unless otherwise stated.</li>
          <li>We reserve the right to change prices at any time without prior notice.</li>
          <li>Orders are subject to availability. We may cancel orders if products become unavailable.</li>
          <li>You are responsible for providing accurate shipping and contact information.</li>
          <li>Risk of loss and title for purchased items pass to you upon delivery to the carrier.</li>
        </ul>
      </Section>

      <Section title="5. Intellectual Property">
        <p>
          All content on this website, including text, graphics, logos, images, numerology
          interpretations, course materials, and software, is the property of Borrowed Curiosity LLC
          or its content creators and is protected by copyright and intellectual property laws.
          You may not reproduce, distribute, or create derivative works without our written permission.
        </p>
      </Section>

      <Section title="6. AI Assistant (Alta)">
        <p>
          Alta is an assistant that provides numerology-related guidance and general
          information. Alta's responses are generated by artificial intelligence and should not
          be considered professional advice (medical, legal, financial, or psychological). Use
          Alta's guidance at your own discretion.
        </p>
      </Section>

      <Section title="7. Free Tools and Calculators">
        <p>
          Our numerology calculators, compatibility tools, and other free features are provided
          for entertainment and self-discovery purposes. Results are based on traditional
          numerological systems and are not scientifically validated. Use them as a guide,
          not a prescription.
        </p>
      </Section>

      <Section title="8. Prohibited Conduct">
        <p>You agree not to:</p>
        <ul>
          <li>Use the site for any illegal or unauthorized purpose.</li>
          <li>Attempt to hack, disrupt, or damage the website or its infrastructure.</li>
          <li>Post spam, malware, or malicious content.</li>
          <li>Scrape, crawl, or harvest data from the site without permission.</li>
          <li>Impersonate another person or entity.</li>
          <li>Use automated tools to interact with the site in ways that degrade service for others.</li>
        </ul>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          Borrowed Curiosity LLC and its owners, employees, and affiliates shall not be liable
          for any indirect, incidental, special, consequential, or punitive damages arising from
          your use of the website or purchase of products. Our total liability for any claim
          shall not exceed the amount you paid for the specific product or service in question.
        </p>
      </Section>

      <Section title="10. Indemnification">
        <p>
          You agree to indemnify and hold harmless Borrowed Curiosity LLC from any claims,
          damages, or expenses arising from your use of the site, violation of these terms,
          or infringement of any rights of a third party.
        </p>
      </Section>

      <Section title="11. Modifications">
        <p>
          We reserve the right to modify these Terms of Service at any time. Changes take effect
          immediately upon posting. Your continued use of the site constitutes acceptance.
        </p>
      </Section>

      <Section title="12. Governing Law">
        <p>
          These terms are governed by and construed in accordance with the laws of the state
          in which Borrowed Curiosity LLC is registered, without regard to conflict of law principles.
        </p>
      </Section>
    </LegalLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-display text-lg font-semibold mb-3">{title}</h2>
      <div className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_li]:leading-relaxed">
        {children}
      </div>
    </div>
  );
}
